apiVersion: v2
name: wallarm-ingress
version: 3.4.10+upstream4.0.16
appVersion: 1.1.1
home: https://github.com/wallarm/ingress
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer with Wallarm module
icon: https://static.wallarm.com/wallarm-logo.svg
keywords:
  - ingress
  - nginx
  - wallarm
sources:
  - https://github.com/wallarm/ingress
type: application
maintainers:
  - name: Wallarm Support Team
    email: support@wallarm.com
engine: gotpl
kubeVersion: ">=1.19.0-0"
