name: Publish Helm
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Extract tag name
        run: echo "X_TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\+.*$//g')" >> $GITHUB_ENV
      -
        name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_PUBLISH_TOKEN }}
          charts_dir: ./charts
          charts_url: https://charts.wallarm.com
          linting: off
          repository: helm-charts
          branch: main
          target_dir: wallarm-ingress
          index_dir: .
          app_version: "${{ env.X_TAG }}"
          chart_version: "${{ env.X_TAG }}"
