name: Publish Helm
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+upstream*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      -
        name: Extract tag name
        run: echo "X_TAG=$(echo ${GITHUB_REF#refs/*/} | sed 's/\+.*$//g')" >> $GITHUB_ENV
      -
        name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_PUBLISH_TOKEN }}
          charts_dir: ./charts
          charts_url: https://charts.wallarm.com
          linting: off
          repository: helm-charts
          branch: main
          target_dir: wallarm-ingress
          index_dir: .
          app_version: "${{ env.X_TAG }}"
          chart_version: "${{ env.X_TAG }}"
      -
        name: Call Wallarm News API
        run: |
          curl \
          --data '{"component_type": "wallarm-ingress-controller", "version": "${{ env.X_TAG }}"}' \
          --header "Authorization: Basic ${{ secrets.NEWS_API_CREDS }}" \
          --header "Content-Type: application/json" \
          --request POST \
          --retry 5 \
          --silent \
          https://api.wallarm.com/v1/versions
